### ISSUE TITLE
Why syncWithCompleteBlock not recommended?

### ISSUE THREAD

**Issue by DragonMeistah** [huynguyencong/NHNetworkTime#8]
In your readME you state that it is better to use an observer to makes updates when sync is completed. You recommend not to use the syncWithComplete block for this. What is the reason that it is not recommended?

**Comment by huynguyencong** [comment]
Why `syncWithComplete:` should call the first time when launch app: Because if user change local time when app is killed, we don't know about it. So we have to sync manually for the first time.

Why `syncWithComplete:` should not call multiple times because:
- It is called automatically if you set `isAutoSynchronizedWhenUserChangeLocalTime = YES` (default is YES, you don't have to do anything)
- `syncWithComplete` should use only if you don't want to update time automatically every local time change
- `syncWithComplete` use network to sync time. It take mobile data and battery. Call it only when you really need (when launch app and auto when user change local time)
- Use `kNHNetworkTimeSyncCompleteNotification`, you can handle the time change everywhere in your code, not only in block

I will update the Readme file, note that should not call it multiple times. And I will remove complete block in `syncWithComplete:`, force use `kNHNetworkTimeSyncCompleteNotification`. It prevent misunderstanding.
Thank you for your question
If you still have the problem, comment below, I will reply soon.

**Comment by DragonMeistah** [comment]
Ok thank you for the explanation. Also after using `syncWithComplete` what is the difference in calling `NHNetworkClock.sharedNetworkClock.networkTime` versus calling `NSDate().networkTime` ? Is one preferred over the other?

**Comment by huynguyencong** [comment]
It is same result. See the implement of [NSDate networkTime] below:

```
+ (NSDate *) networkDate {
  return [[NHNetworkClock sharedNetworkClock] networkTime];
}
```

But I prefer use `[NSDate networkTime]` for shorter and more readable code.

**Comment by huynguyencong** [comment]
Updated. Please review read me file
